### ISSUE TITLE
How to add Listview as ChildView

### ISSUE THREAD

**Issue by shoebhoney** [thewaychung/ExpandableGridView#2]
Hi Chung,

Very Great work!!

I need to add a listview as child view.
Can you please suggest me how to do that.

Many Thankful to you in advance.

**Comment by thewaychung** [comment]
If you want add a ListView as child, then you may need to modify some code. Set the child view to `ListView` and reset the chid view's height.
1.  Change child view's height. In line 91 `'int middleViewHeight = clickedView.getHeight()+20;'`, the height is set to GridView item's height add 20 by default. You may change it to what you want.
2. Change the child view from `GridView` to `ListView` in line 135.

By doing these steps, I think it should work.
